Repository sod2003/Team_Spring_Spartans, pull requests merged in 2024-02, with the labels that each got.

#1 Completed readme.
  README.md
Labels: documentation

#4 Adding base models for project.
  src/main/java/com/skillstorm/spartanwireless/models/Customer.java
  src/main/java/com/skillstorm/spartanwireless/models/Device.java
  src/main/java/com/skillstorm/spartanwireless/models/PhoneLine.java
  src/main/java/com/skillstorm/spartanwireless/models/PhoneLineId.java
  src/main/java/com/skillstorm/spartanwireless/models/PhonePlan.java
Labels: enhancement

#5 Bug Fix: Phone Line Model now uses phone number as the PK.
  src/main/java/com/skillstorm/spartanwireless/models/Customer.java
  src/main/java/com/skillstorm/spartanwireless/models/Device.java
  src/main/java/com/skillstorm/spartanwireless/models/PhoneLine.java
  src/main/java/com/skillstorm/spartanwireless/models/PhoneLineId.java
Labels: bug

#6 Adding Test Data SQL script
  src/main/resources/PopulateData.sql
Labels: sql

#14 Added name field to customer api and test success all endpoints
  src/main/java/com/skillstorm/spartanwireless/dtos/CustomerRequestDto.java
  src/main/java/com/skillstorm/spartanwireless/dtos/CustomerResponseDto.java
  src/main/java/com/skillstorm/spartanwireless/mappers/CustomerMapper.java
  src/main/java/com/skillstorm/spartanwireless/models/Customer.java
Labels: enhancement

#15 Add isArchived feature.
  src/main/java/com/skillstorm/spartanwireless/dtos/CustomerResponseDto.java
  src/main/java/com/skillstorm/spartanwireless/mappers/CustomerMapper.java
  src/main/java/com/skillstorm/spartanwireless/models/Customer.java
  src/main/java/com/skillstorm/spartanwireless/services/CustomerService.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/CustomerServiceImpl.java
Labels: enhancement

#16 Refractored PhonePlan API, added custom query, made logical reference…
  src/main/java/com/skillstorm/spartanwireless/controllers/PhonePlanController.java
  src/main/java/com/skillstorm/spartanwireless/dtos/PhonePlanResponseDto.java
  src/main/java/com/skillstorm/spartanwireless/exceptions/GlobalExceptionHandler.java
  src/main/java/com/skillstorm/spartanwireless/exceptions/PhonePlanNotPurchasedException.java
  src/main/java/com/skillstorm/spartanwireless/mappers/PhonePlanMapper.java
  src/main/java/com/skillstorm/spartanwireless/repositories/PhonePlanRepository.java
  src/main/java/com/skillstorm/spartanwireless/services/PhonePlanService.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/PhonePlanServiceImpl.java
Labels: enhancement

#17 Test standards
  src/main/java/com/skillstorm/spartanwireless/controllers/PhonePlanController.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/CustomerServiceImpl.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/DeviceServiceImpl.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/PhoneLineServiceImpl.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/PhonePlanServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/repositories/TestCustomerRepo.java
  src/test/java/com/skillstorm/spartanwireless/resources/PopulateData.sql
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestCustomerServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestDeviceServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhoneLineServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhonePlanServiceImpl.java
Labels: enhancement
