Repository sod2003/Team_Spring_Spartans, pull requests merged in 2024-03, with the labels that each got.

#19 TestDeviceServiceImpl implementation
  src/main/java/com/skillstorm/spartanwireless/dtos/DeviceRequestDto.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestDeviceServiceImpl.java
Labels: enhancement

#20 Test customer service impl
  src/main/java/com/skillstorm/spartanwireless/controllers/CustomerController.java
  src/main/java/com/skillstorm/spartanwireless/dtos/CustomerRequestDto.java
  src/main/java/com/skillstorm/spartanwireless/dtos/CustomerResponseDto.java
  src/main/java/com/skillstorm/spartanwireless/mappers/CustomerMapper.java
  src/main/java/com/skillstorm/spartanwireless/services/CustomerService.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/CustomerServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/repositories/TestCustomerRepo.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestCustomerServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhonePlanServiceImpl.java
Labels: enhancement, test

#25 Init angular project inside /front_end
  front_end/.editorconfig
  front_end/.gitignore
  front_end/README.md
  front_end/angular.json
  front_end/package-lock.json
  front_end/package.json
  front_end/src/app/app.component.css
  front_end/src/app/app.component.html
  front_end/src/app/app.component.spec.ts
  front_end/src/app/app.component.ts
  front_end/src/app/app.config.ts
  front_end/src/app/app.routes.ts
  front_end/src/assets/.gitkeep
  front_end/src/favicon.ico
  front_end/src/index.html
  front_end/src/main.ts
  front_end/src/styles.css
  front_end/tsconfig.app.json
  front_end/tsconfig.json
  front_end/tsconfig.spec.json
Labels: enhancement

#22 Feature get customer phone lines and devices
  src/main/java/com/skillstorm/spartanwireless/controllers/PhoneLineController.java
  src/main/java/com/skillstorm/spartanwireless/dtos/DeviceRequestDto.java
  src/main/java/com/skillstorm/spartanwireless/dtos/PhoneLineRequestDto.java
  src/main/java/com/skillstorm/spartanwireless/dtos/PhoneLineResponseDto.java
  src/main/java/com/skillstorm/spartanwireless/mappers/DeviceMapper.java
  src/main/java/com/skillstorm/spartanwireless/mappers/PhoneLineMapper.java
  src/main/java/com/skillstorm/spartanwireless/models/Customer.java
  src/main/java/com/skillstorm/spartanwireless/models/Device.java
  src/main/java/com/skillstorm/spartanwireless/models/PhoneLine.java
  src/main/java/com/skillstorm/spartanwireless/repositories/PhoneLineRepository.java
  src/main/java/com/skillstorm/spartanwireless/services/PhoneLineService.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/DeviceServiceImpl.java
  src/main/java/com/skillstorm/spartanwireless/services/impl/PhoneLineServiceImpl.java
Labels: enhancement

#27 Built Backend service for front_end. Tested routes through to database.
  front_end/src/app/app.config.ts
  front_end/src/app/app.routes.ts
  front_end/src/app/services/backend.service.spec.ts
  front_end/src/app/services/backend.service.ts
  front_end/src/app/test/test.component.css
  front_end/src/app/test/test.component.html
  front_end/src/app/test/test.component.spec.ts
  front_end/src/app/test/test.component.ts
  src/main/java/com/skillstorm/spartanwireless/controllers/CustomerController.java
  src/main/resources/PopulateData.sql
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhoneLineServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhonePlanServiceImpl.java
Labels: enhancement, test

#29 Test phone plan service
  front_end/angular.json
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestCustomerServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhonePlanServiceImpl.java
Labels: test

#26 PhoneLineServiceImpl tests are built out, but they currently don't wo…
  src/main/java/com/skillstorm/spartanwireless/dtos/PhoneLineRequestDto.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhoneLineServiceImpl.java
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhonePlanServiceImpl.java
Labels: test

#30 Demonstrating front-end routing.
  front_end/src/app/services/backend.service.ts
  front_end/src/app/test/test.component.ts
  src/main/java/com/skillstorm/spartanwireless/controllers/CustomerController.java
  src/main/java/com/skillstorm/spartanwireless/controllers/DeviceController.java
Labels: enhancement

#32 Feature device model route
  front_end/src/app/app.routes.ts
  front_end/src/app/models/device.spec.ts
  front_end/src/app/models/device.ts
  front_end/src/app/services/device.service.spec.ts
  front_end/src/app/services/device.service.ts
  front_end/src/app/test/testdevice/testdevice.component.css
  front_end/src/app/test/testdevice/testdevice.component.html
  front_end/src/app/test/testdevice/testdevice.component.spec.ts
  front_end/src/app/test/testdevice/testdevice.component.ts
  src/main/java/com/skillstorm/spartanwireless/controllers/DeviceController.java
Labels: enhancement

#33 Refactored customerService on the frontend.
  front_end/src/app/services/customer.service.ts
  front_end/src/app/test/test.component.ts
  src/main/java/com/skillstorm/spartanwireless/controllers/CustomerController.java
  src/main/resources/PopulateData.sql
Labels: bug, enhancement

#35 PhoneLine model and mapping: Frontend
  front_end/src/app/app.routes.ts
  front_end/src/app/models/phoneline.spec.ts
  front_end/src/app/models/phoneline.ts
  front_end/src/app/services/phoneline.service.spec.ts
  front_end/src/app/services/phoneline.service.ts
  front_end/src/app/test/testphoneline/testphoneline.component.css
  front_end/src/app/test/testphoneline/testphoneline.component.html
  front_end/src/app/test/testphoneline/testphoneline.component.spec.ts
  front_end/src/app/test/testphoneline/testphoneline.component.ts
  src/main/java/com/skillstorm/spartanwireless/controllers/PhoneLineController.java
Labels: enhancement

#23 Security Dependency established, Initial WebSecurityConfig built.
  pom.xml
  src/main/java/com/skillstorm/spartanwireless/config/WebSecurityConfig.java
  src/main/java/com/skillstorm/spartanwireless/models/Customer.java
  src/main/java/com/skillstorm/spartanwireless/models/User.java
  src/main/resources/PopulateData.sql
Labels: enhancement

#39 Adding Phonelines component to Dashboard.
  front_end/src/app/components/phone-lines/phone-lines.component.css
  front_end/src/app/components/phone-lines/phone-lines.component.html
  front_end/src/app/components/phone-lines/phone-lines.component.spec.ts
  front_end/src/app/components/phone-lines/phone-lines.component.ts
  front_end/src/app/pages/dashboard/dashboard.component.html
  front_end/src/app/services/phoneline.service.ts
Labels: enhancement

#40 Working on phone line with Sean
  front_end/src/app/components/bill/bill.component.html
  front_end/src/app/components/bill/bill.component.ts
  front_end/src/app/components/phone-lines/phone-lines.component.html
  front_end/src/app/components/phone-lines/phone-lines.component.ts
  front_end/src/app/components/phone-plans/phone-plans.component.html
  front_end/src/app/pages/dashboard/dashboard.component.ts
  front_end/src/app/services/device.service.ts
Labels: enhancement

#41 Implemented CrytoJS to finish auth, staying logged in, logout
  front_end/src/app/components/bill/bill.component.html
  front_end/src/app/components/header/header.component.html
  front_end/src/app/components/header/header.component.ts
  front_end/src/app/pages/dashboard/dashboard.component.html
  front_end/src/app/pages/dashboard/dashboard.component.ts
  front_end/src/app/services/auth.service.ts
  front_end/src/app/services/customer.service.ts
  front_end/src/environments/environment.production.ts
  src/main/java/com/skillstorm/spartanwireless/config/WebSecurityConfig.java
  src/main/java/com/skillstorm/spartanwireless/controllers/LoginController.java
Labels: enhancement

#43 Updating Phone Line Component
  .gitignore
  front_end/package.json
  front_end/src/app/components/bill/bill.component.html
  front_end/src/app/components/phone-lines/phone-lines.component.ts
  front_end/src/app/pages/dashboard/dashboard.component.html
  src/main/resources/PopulateData.sql
Labels: enhancement

#44 Second revision to the README
  README.md
Labels: documentation

#48 Feature buy phone plans
  front_end/src/app/components/bill/bill.component.html
  front_end/src/app/components/bill/bill.component.ts
  front_end/src/app/components/devices/devices.component.html
  front_end/src/app/components/devices/devices.component.ts
  front_end/src/app/components/header/header.component.ts
  front_end/src/app/components/phone-lines/phone-lines.component.html
  front_end/src/app/components/phone-lines/phone-lines.component.ts
  front_end/src/app/components/phone-plans-buy/phone-plans-buy.component.css
  front_end/src/app/components/phone-plans-buy/phone-plans-buy.component.html
  front_end/src/app/components/phone-plans-buy/phone-plans-buy.component.spec.ts
  front_end/src/app/components/phone-plans-buy/phone-plans-buy.component.ts
  front_end/src/app/components/phone-plans/phone-plans.component.html
  front_end/src/app/components/phone-plans/phone-plans.component.ts
  front_end/src/app/pages/dashboard/dashboard.component.html
  front_end/src/app/pages/dashboard/dashboard.component.ts
  front_end/src/app/services/phone-plan.service.ts
  front_end/src/app/services/phoneline.service.ts
  src/main/java/com/skillstorm/spartanwireless/controllers/PhonePlanController.java
Labels: enhancement

#50 Bug fixmerge2
  front_end/src/app/pages/dashboard/dashboard.component.html
  front_end/src/app/services/phoneline.service.ts
Labels: bug

#51 created phone number generator api
  front_end/.gitignore
  front_end/src/app/components/devices/devices.component.ts
  front_end/src/app/components/phone-lines/phone-lines.component.html
  front_end/src/app/components/phone-lines/phone-lines.component.ts
  front_end/src/app/pipes/phone-number-formatter.pipe.spec.ts
  front_end/src/app/pipes/phone-number-formatter.pipe.ts
  front_end/src/app/services/phoneline.service.ts
Labels: enhancement

#52 Bug: Max Lines
  front_end/src/app/components/devices/devices.component.html
  front_end/src/app/components/devices/devices.component.ts
  front_end/src/app/components/phone-lines/phone-lines.component.html
  front_end/src/app/components/phone-lines/phone-lines.component.ts
  front_end/src/app/pages/dashboard/dashboard.component.html
  front_end/src/app/pages/dashboard/dashboard.component.ts
Labels: bug

#57 Fixed phoneline backend tests after DTO changes.
  src/test/java/com/skillstorm/spartanwireless/services/impl/TestPhoneLineServiceImpl.java
Labels: test
